language: python
python:
- '3.8'
services:
- docker
before_script: pip install docker-compose
scripts:
- docker-compose run app sh -c "python manage.py test && flake8"
deploy:
  provider: heroku
  api_key:
    secure: U0MX1muCp6h90N0bdiNWIF5YcMehAzBQ0RqddE+P5ScaJd2oImX5VWnSR4+WNmgL62ywZ7jqwm+OLfi5WuYZuBZQ9VEgLED6UPyXSF0B8FIAHw3vLgwYknbiUNf8Y18NQ5wRlRBDhbHN+VbX8wGpEj0NeuRak9MUFFP0IVfWYPBTAFmgcdUaWGCch06Ydj5LRPVYzRkAO4RzDadXq8TI+I8azLa05Pqg8HVmynh58pJ2ArAeFEsshji0qApOgaQ/RVy71MK7iZPl1CCZZMnKYqMzyjQbhWxSaBwqo7JX3RU/21vJlJDm/BRc3rGYrFMqClpOgKEH3th/KWQVCCN/ojmtHOzmkiBI8CZuIp7SMokm6h+ZRGr00qHpfGDczzZcCNPbrFbiaC8BopEm9CAOUx/pVu+8Yc3xg5dXEd94WWE1TTVbB8J0w49BK/4ypzzg08nFp9HroXLt8lHY3Ri4oGq6GbDOJnD8z/Cs0fAe6+EWTMNKXy5s7CXqE7NjKvqeumZ+/M/YOfqHdRXbg5DDyj24oejg/r8pcVDTjZGOymGmQwARtdtBOPDgYlJfkMIFHN5CWKNBY9xKc6A1oU/tLveKcfQGji7KHoq6Lo4V4Lrrd2WKFZfUefZfESK7DMTvlVPAFbTX5TRmLSoo3Nw7aG2937/S3fgmj1rs30XoyGo=
  on:
    branch: main
