# Generated by Django 2.1.15 on 2020-10-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Equipments',
            new_name='Equipment',
        ),
        migrations.DeleteModel(
            name='Vessels',
        ),
    ]
