# Generated by Django 2.1.15 on 2020-10-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201012_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
